service: chatbot-api

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  memorySize: 4096
  timeout: 30

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: app.app
  pythonRequirements:
    dockerizePip: true

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
